// Topic pairs -- the majority get `main`, exactly 2 players (the imposters)
// get `imposter` instead. The two must be close enough that an imposter's
// words could plausibly fit the main topic too.
const TOPIC_PAIRS = [
  { main: "Coffee", imposter: "Tea" },
  { main: "Beach", imposter: "Lake" },
  { main: "Pizza", imposter: "Burger" },
  { main: "Cat", imposter: "Dog" },
  { main: "Summer", imposter: "Spring" },
  { main: "Basketball", imposter: "Volleyball" },
  { main: "Guitar", imposter: "Violin" },
  { main: "Doctor", imposter: "Nurse" },
  { main: "Ocean", imposter: "River" },
  { main: "Airplane", imposter: "Helicopter" },
  { main: "Pen", imposter: "Pencil" },
  { main: "Rain", imposter: "Snow" },
  { main: "Butterfly", imposter: "Moth" },
  { main: "Sofa", imposter: "Armchair" },
  { main: "Train", imposter: "Bus" },
  { main: "Mountain", imposter: "Hill" },
  { main: "Chess", imposter: "Checkers" },
  { main: "Ice Cream", imposter: "Frozen Yogurt" },
  { main: "Wolf", imposter: "Fox" },
  { main: "Lion", imposter: "Tiger" },
  { main: "Piano", imposter: "Keyboard" },
  { main: "Library", imposter: "Bookstore" },
  { main: "Teacher", imposter: "Professor" },
  { main: "Pancakes", imposter: "Waffles" },
  { main: "Soda", imposter: "Juice" },
  { main: "Skiing", imposter: "Snowboarding" },
  { main: "Castle", imposter: "Palace" },
  { main: "Butter", imposter: "Margarine" },
  { main: "Rabbit", imposter: "Hare" },
  { main: "Football", imposter: "Rugby" },
  { main: "Sushi", imposter: "Sashimi" },
  { main: "Camera", imposter: "Phone" },
  { main: "Umbrella", imposter: "Raincoat" },
  { main: "Motorcycle", imposter: "Bicycle" },
  { main: "Volcano", imposter: "Earthquake" },
  { main: "Sandwich", imposter: "Wrap" },
  { main: "Owl", imposter: "Eagle" },
  { main: "Candle", imposter: "Lantern" },
  { main: "Snowman", imposter: "Igloo" },
  { main: "Backpack", imposter: "Suitcase" },
  { main: "Waterfall", imposter: "Rapids" },
];

module.exports = TOPIC_PAIRS;
