// A curated list of common 5-letter English words -- used both as the pool
// of secret answers and as the "allowed guess" dictionary. This is not the
// full Wordle dictionary (that's tens of thousands of words and isn't
// something we can bundle/verify offline), but it's large enough for varied,
// replayable rounds of real, guessable words.
const WORDS = [
  "aback", "abide", "abode", "abort", "about", "above", "abuse", "acorn", "acute", "adapt",
  "admit", "adopt", "adult", "after", "again", "agent", "agile", "agree", "ahead", "alarm",
  "album", "alert", "alike", "alive", "allow", "alone", "along", "aloud", "alpha", "altar",
  "alter", "among", "amuse", "angel", "anger", "angle", "angry", "ankle", "apple", "apply",
  "arena", "argue", "arise", "armor", "aroma", "array", "arrow", "aside", "asset", "atlas",
  "audio", "audit", "avoid", "await", "awake", "award", "aware", "awful", "bacon", "badge",
  "baker", "basic", "basin", "basis", "batch", "beach", "beard", "beast", "began", "begin",
  "being", "below", "bench", "berry", "birth", "black", "blade", "blame", "blank", "blast",
  "blaze", "bleed", "blend", "bless", "blind", "blink", "block", "blood", "bloom", "board",
  "boast", "bonus", "boost", "booth", "bound", "brain", "brake", "brand", "brave", "bread",
  "break", "breed", "brick", "bride", "brief", "bring", "broad", "broke", "brown", "brush",
  "build", "built", "bunch", "burst", "cabin", "cable", "candy", "canoe", "cargo",
  "carry", "carve", "catch", "cause", "chain", "chair", "chalk", "champ", "chaos", "charm",
  "chart", "chase", "cheap", "check", "cheer", "chess", "chest", "chief", "child", "chill",
  "choir", "choke", "chord", "chose", "civic", "civil", "claim", "clash", "class", "clean",
  "clear", "clerk", "click", "cliff", "climb", "cling", "clock", "clone", "close", "cloth",
  "cloud", "clown", "coach", "coast", "cobra", "colon", "color", "comet", "comic", "coral",
  "couch", "could", "count", "court", "cover", "crack", "craft", "crane", "crash", "crate",
  "crave", "crawl", "crazy", "cream", "creek", "creep", "crest", "crime", "crisp", "cross",
  "crowd", "crown", "crude", "cruel", "crush", "crust", "curly", "curse", "curve", "cycle",
  "daily", "dairy", "dance", "dandy", "dealt", "death", "debut", "decay", "delay", "delta",
  "demon", "dense", "depth", "derby", "devil", "diary", "digit", "diner", "dirty", "ditch",
  "diver", "dodge", "donor", "donut", "doubt", "dough", "dozen", "draft", "drain", "drama",
  "drank", "drawn", "dread", "dream", "dress", "dried", "drift", "drill", "drink", "drive",
  "drove", "drown", "duchy", "dusty", "dwell", "eager", "eagle", "early", "earth", "eight",
  "elbow", "elder", "elect", "elite", "empty", "enemy", "enjoy", "enter", "entry", "equal",
  "equip", "erase", "error", "essay", "event", "every", "exact", "exist", "exile", "expel",
  "extra", "fable", "faith", "false", "fancy", "fatal", "fault", "favor", "feast", "fence",
  "ferry", "fever", "fiber", "field", "fiery", "fifth", "fifty", "fight", "final", "first",
  "fixed", "flame", "flash", "fleet", "flesh", "flick", "flint", "float", "flock", "flood",
  "floor", "flour", "fluid", "flush", "flute", "focus", "foggy", "force", "forge", "forth",
  "forty", "forum", "found", "frame", "frank", "fraud", "fresh", "front", "frost", "frown",
  "fruit", "fudge", "fully", "fungi", "funny", "furry", "fuzzy", "gamer", "genre", "ghost",
  "giant", "given", "glass", "glide", "globe", "glory", "glove", "going", "grace", "grade",
  "grain", "grand", "grant", "grape", "graph", "grasp", "grass", "grave", "great", "greed",
  "green", "greet", "grief", "grill", "grind", "groom", "gross", "group", "grove",
  "grown", "guard", "guess", "guest", "guide", "habit", "happy", "harsh", "haste", "hasty",
  "hatch", "haunt", "haven", "heart", "heavy", "hedge", "hello", "hence", "hobby", "honey",
  "honor", "horse", "hotel", "house", "human", "humid", "humor", "hunch", "hunts", "husky",
  "hydro", "ideal", "idiom", "image", "index", "inner", "input", "inter", "issue", "ivory",
  "jelly", "jewel", "joint", "joker", "judge", "juice", "jumbo", "jumpy", "kayak",
  "kneel", "knife", "knock", "known", "label", "labor", "laden", "lance", "large", "laser",
  "latch", "later", "laugh", "layer", "learn", "lease", "least", "leave", "legal", "lemon",
  "level", "lever", "light", "limit", "linen", "liver", "lobby", "local", "logic", "loose",
  "lorry", "lower", "loyal", "lucky", "lunar", "lunch", "lyric", "magic", "major", "maker",
  "mango", "maple", "march", "marsh", "match", "maybe", "mayor", "medal", "media", "melon",
  "mercy", "merge", "merit", "merry", "metal", "meter", "metro", "might", "minor", "minus",
  "mixer", "model", "money", "month", "moral", "motor", "mount", "mouse", "mouth", "movie",
  "music", "naive", "naked", "nasty", "nerve", "never", "newly", "night", "noble", "noise",
  "north", "novel", "nurse", "ocean", "offer", "often", "olive", "onion", "opera", "orbit",
  "order", "organ", "other", "ought", "ounce", "outer", "owner", "oxide", "ozone", "paint",
  "panel", "panic", "paper", "party", "pasta", "patch", "pause", "peace", "peach", "pearl",
  "phase", "phone", "photo", "piano", "piece", "pilot", "pitch", "pizza", "place", "plain",
  "plane", "plant", "plate", "plaza", "plots", "plumb", "point", "poker", "polar", "porch",
  "power", "press", "price", "pride", "prime", "print", "prior", "prism", "prize", "proof",
  "proud", "prove", "pulse", "punch", "pupil", "puppy", "purse", "quart", "quash", "queen",
  "query", "quest", "quick", "quiet", "quilt", "quirk", "quill", "quote", "radio", "raise",
  "rally", "ranch", "range", "rapid", "ratio", "reach", "react", "ready", "realm", "rebel",
  "refer", "reign", "relax", "reply", "reset", "resin", "rider", "ridge", "rifle", "right",
  "rigid", "rival", "river", "roast", "robin", "robot", "rocky", "roman", "rough", "round",
  "route", "rover", "royal", "rugby", "ruler", "rumor", "rural", "sadly", "salad", "salon",
  "salsa", "salty", "sandy", "sauce", "scale", "scarf", "scary", "scene", "scent", "scoop",
  "scope", "score", "scout", "scrap", "screw", "seven", "shade", "shaft", "shake", "shale",
  "shall", "shape", "share", "shark", "sharp", "shave", "shelf", "shell", "shift", "shine",
  "shiny", "shirt", "shock", "shoot", "shore", "short", "shout", "shown", "shrug", "sight",
  "silky", "since", "sixth", "sixty", "skate", "skill", "skirt", "skull", "slate", "sleep",
  "slice", "slide", "slime", "slope", "small", "smart", "smell", "smile", "smoke", "snack",
  "snake", "sniff", "solar", "solid", "solve", "sonic", "sorry", "sound", "south", "space",
  "spare", "spark", "speak", "spear", "speed", "spell", "spend", "spice", "spicy", "spike",
  "spine", "spite", "split", "spoil", "spoke", "sport", "spray", "squad", "stack", "staff",
  "stage", "stain", "stair", "stake", "stale", "stall", "stamp", "stand", "stare", "start",
  "state", "steak", "steal", "steam", "steel", "steep", "steer", "stern", "stick", "stiff",
  "still", "sting", "stock", "stone", "stool", "store", "storm", "story", "stout", "stove",
  "strap", "straw", "stray", "strip", "study", "stuff", "style", "sugar", "suite", "sunny",
  "super", "surge", "swamp", "swear", "sweat", "sweep", "sweet", "swift", "swing", "sword",
  "table", "taste", "teach", "tempo", "tenth", "thank", "theme", "there", "thick", "thief",
  "thing", "think", "third", "those", "three", "throw", "thumb", "tiger", "tight", "timer",
  "tired", "title", "toast", "today", "token", "tooth", "topic", "torch", "total", "touch",
  "tough", "tower", "toxic", "trace", "track", "trade", "trail", "train", "trait", "trash",
  "treat", "trend", "trial", "tribe", "trick", "troop", "truck", "truly", "trunk", "trust",
  "truth", "tulip", "tumor", "tutor", "twice", "twist", "umbra", "uncle", "under", "union",
  "unite", "unity", "until", "upper", "upset", "urban", "usage", "usual", "vague", "valid",
  "valor", "value", "valve", "vapor", "vault", "vegan", "venue", "verse", "video", "villa",
  "vinyl", "viral", "virus", "visit", "vital", "vivid", "vocal", "voice", "voter", "wagon",
  "waste", "watch", "water", "weave", "weird", "whale", "wheat", "wheel", "where", "which",
  "while", "white", "whole", "whose", "widow", "width", "witch", "world", "worry", "worse",
  "worst", "worth", "would", "wound", "wrist", "write", "wrong", "wrote", "yield", "young",
  "youth", "zebra",
];

module.exports = WORDS;
