module.exports = {
  "Connect 4": require("./connect4"),
  "Chess": require("./chess"),
  "Tic Tac Toe": require("./tictactoe"),
  "Catan": require("./catan/engine"),
  "One and Only": require("./oneandonly/engine"),
  "Andhra Business": require("./andhrabusiness/engine"),
  "Snakes and Ladders": require("./snakesandladders/engine"),
  "Ludo": require("./ludo/engine"),
  "Word Rush": require("./wordrush/engine"),
  "Imposter": require("./imposter/engine"),
  "Pictionary": require("./pictionary/engine"),
  "Checkers": require("./checkers"),
  "Guess Who": require("./guesswho"),
  "Tambola": require("./tambola"),
};
